# Generated by Django 4.0 on 2021-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestProperity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Propertymage')),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, default=0, null=True)),
                ('beds', models.IntegerField(blank=True, default=0, null=True)),
                ('baths', models.IntegerField(blank=True, default=0, null=True)),
                ('garages', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
